/**
 * AgenturOS Design System ÔÇô zentrale Klassen-Konstanten f├╝r TypeScript-Komponenten.
 * Entspricht den Utilities in src/styles/design-components.css.
 */

export const aosFocusRingClassName = 'aos-focus-ring'
export const aosTransitionClassName = 'aos-transition'

export const aosTextDisplayClassName = 'aos-text-display'
export const aosTextPageTitleClassName = 'aos-text-page-title'
export const aosTextSectionTitleClassName = 'aos-text-section-title'
export const aosTextCardTitleClassName = 'aos-text-card-title'
export const aosTextBodyClassName = 'aos-text-body'
export const aosTextSmallClassName = 'aos-text-small'
export const aosTextCaptionClassName = 'aos-text-caption'
export const aosTextLabelClassName = 'aos-text-label'
export const aosTextLabelSmClassName = 'aos-text-label-sm'
export const aosTextMetaClassName = 'aos-text-meta'

export const aosInputClassName = 'aos-input'
export const aosInputLgClassName = 'aos-input aos-input-lg'
export const aosTextareaClassName = 'aos-textarea'
export const aosSelectClassName = 'aos-select'
export const aosSelectTouchClassName = 'aos-select-touch'

export const aosBtnClassName = 'aos-btn'
export const aosBtnPrimaryClassName = 'aos-btn-primary'
export const aosBtnPrimaryLgClassName = 'aos-btn-primary-lg'
export const aosBtnSecondaryClassName = 'aos-btn-secondary'
export const aosBtnSecondaryLgClassName = 'aos-btn-secondary-lg'
export const aosBtnGhostClassName = 'aos-btn-ghost'
export const aosBtnGhostLgClassName = 'aos-btn-ghost-lg'
export const aosBtnDangerClassName = 'aos-btn-danger'
export const aosBtnSmClassName = 'aos-btn-sm'
export const aosBtnXsClassName = 'aos-btn-xs'
export const aosIconButtonClassName = 'aos-icon-button'

export const aosCardClassName = 'aos-card'
export const aosCardPaddedClassName = 'aos-card-padded'
export const aosCardPanelClassName = 'aos-card-panel'
export const aosWorkspaceSurfaceClassName = 'aos-workspace-surface'
export const aosCardEmptyClassName = 'aos-card-empty'
export const aosPanelHeaderClassName = 'aos-panel-header'
export const aosPanelFooterClassName = 'aos-panel-footer'

export const aosBadgeClassName = 'aos-badge'
export const aosBadgeNeutralClassName = 'aos-badge-neutral'
export const aosBadgeNeutralSubduedClassName = 'aos-badge-neutral-subdued'
export const aosBadgeEmphasisClassName = 'aos-badge-emphasis'

export const aosAlertErrorClassName = 'aos-alert-error'
export const aosAlertWarningClassName = 'aos-alert-warning'
export const aosAlertSuccessClassName = 'aos-alert-success'
export const aosAlertInfoClassName = 'aos-alert-info'

export const aosLinkClassName = 'aos-link'
export const aosLinkInlineClassName = 'aos-link-inline'

export const aosDialogOverlayClassName = 'aos-dialog-overlay'
export const aosDialogPanelClassName = 'aos-dialog-panel'
export const aosDialogPanelLgClassName = 'aos-dialog-panel-lg'
export const aosDropdownPanelClassName = 'aos-dropdown-panel'

export const aosListSelectedClassName = 'aos-list-selected'
export const aosListContainerClassName = 'aos-list-container'

export const aosEmptyStateClassName = 'aos-empty-state'
export const aosSkeletonClassName = 'aos-skeleton'
export const aosSkeletonSubtleClassName = 'aos-skeleton-subtle'

export const aosFieldErrorClassName = 'aos-field-error'
export const aosFieldErrorSmClassName = 'aos-field-error-sm'

export const aosAppSidebarClassName = 'aos-app-sidebar'
export const aosAppHeaderClassName = 'aos-app-header'
export const aosWorkspacePageClassName = 'aos-workspace-page'
export const aosWorkspacePageCompactClassName = 'aos-workspace-page-compact'
export const aosWorkspacePageHeaderClassName = 'aos-workspace-page-header'
export const aosWorkspaceChromeClassName = 'aos-workspace-chrome'
export const aosWorkspaceChromeTitleClassName = 'aos-workspace-chrome-title'
export const aosWorkspaceToolbarClassName = 'aos-workspace-toolbar'
export const aosWorkspaceToolbarMetaClassName = 'aos-workspace-toolbar-meta'
export const aosWorkspaceToolbarActionsClassName = 'aos-workspace-toolbar-actions'
export const aosWorkspaceBodyClassName = 'aos-workspace-body'
export const aosWorkspaceBodyCompactClassName = 'aos-workspace-body-compact'
export const aosWorkspaceSplitClassName = 'aos-workspace-split'
export const aosWorkspaceListPaneClassName = 'aos-workspace-list-pane'
export const aosWorkspaceListScrollClassName = 'aos-workspace-list-scroll'
export const aosWorkspaceDetailPaneClassName = 'aos-workspace-detail-pane'
export const aosNavGroupLabelClassName = 'aos-nav-group-label'
export const aosNavLinkClassName = 'aos-nav-link'
export const aosNavLinkActiveClassName = 'aos-nav-link-active'
export const aosNavLinkIndicatorClassName = 'aos-nav-link-indicator'
export const aosSidebarUserClassName = 'aos-sidebar-user'
export const aosCaptureSidebarClassName = 'aos-capture-sidebar'
export const aosCaptureFloatingClassName = 'aos-capture-floating'
export const aosCaptureFloatingBtnClassName = 'aos-capture-floating-btn'
