export { WorkspaceFrame } from '@/components/app/workspace/workspace-frame'
export { WorkspacePageHeader } from '@/components/app/workspace/workspace-page-header'
export { WorkspaceSectionHeading } from '@/components/app/workspace/workspace-section-heading'
export { WorkspaceSplit } from '@/components/app/workspace/workspace-split'
export { WorkspaceToolbar } from '@/components/app/workspace/workspace-toolbar'
